### ISSUE TITLE
Is it normal that simulator only generates 7 types of messages?

### ISSUE THREAD

**Issue by bnsblue** [openxc/openxc-vehicle-simulator#40] opened 2017-08-31 02:49 UTC
I am new to openxc and am ramping up by trying out the simulator with openxc-python.

The simulator and openxc-python are installed without any problem. After getting the simulator up and running at localhost:50001, when using `openxc-dump --network`, however, I can only see 7 types of messages being dumped repeatedly.
They are: four `door_status`, (`passenger`, `driver`, `right_rear`, `left_rear`), one `headlamp_status`, one `high_beam_status`, and one `windshield_wiper_status`, as shown in the following screenshot.

![image](https://user-images.githubusercontent.com/1518524/29903713-3c5be966-8dd3-11e7-8cf5-3c1830a69fe4.png)

The changes of the values of these attributes (door status, headlamp_status, high_beam_status, windshield_wipter_status) are reflected in the dumped trace, but none of the other predefined attributes (e.g., Gear Level, steering wheel angle, etc.) can be observed from the trace even when I change the value in the web UI. The only exceptions are the `custom messages`, which will actually show up in the dumped trace.

I am wondering if this is normal. If no, may I request for some pointer about what I might did wrong? 

Any suggestion is much appreciated!

Edit: I am running everything on a Mac (macOS 10.12.6).  The version of the openxc-python is 0.13 (installed via pip). The simulator is built manually from this repo. Python version 2.7.13.

**Comment by emarsman** [comment] 2017-08-31 17:12
No, this is not normal. I just checked and I get everything running 0.13 python with current master of simulator on Windows 7. I don't see how you would get some signals and not others. 

Below is my output. I will close this issues since I can't reproduce it. If you are still having issues, we can debug together. Let's move the conversation over the google group though. Feel free to copy & paste this and start a conversation there. 

Regards,
Eric

$ openxc-dump --network
Opened socket connection at 192.168.56.1:50001
<SourceLogger(Thread-2, started daemon 14392)> doesn't support logging
{"timestamp": 1504199167.067, "name": "fuel_level", "value": 99.0}
{"timestamp": 1504199167.157, "name": "steering_wheel_angle", "value": 0.0}
{"timestamp": 1504199167.158, "name": "torque_at_transmission", "value": 0.0}
{"timestamp": 1504199167.159, "name": "engine_speed", "value": 0.0}
{"timestamp": 1504199167.16, "name": "vehicle_speed", "value": 0.0}
{"timestamp": 1504199167.161, "name": "accelerator_pedal_position", "value": 0.0}
{"timestamp": 1504199167.162, "name": "odometer", "value": 0.0}
{"timestamp": 1504199167.163, "name": "fuel_consumed_since_restart", "value": 0.10317}
{"timestamp": 1504199167.267, "name": "steering_wheel_angle", "value": 0.0}
{"timestamp": 1504199167.268, "name": "torque_at_transmission", "value": 0.0}
{"timestamp": 1504199167.269, "name": "engine_speed", "value": 0.0}
{"timestamp": 1504199167.27, "name": "vehicle_speed", "value": 0.0}
{"timestamp": 1504199167.271, "name": "accelerator_pedal_position", "value": 0.0}
{"timestamp": 1504199167.272, "name": "odometer", "value": 0.0}
{"timestamp": 1504199167.273, "name": "fuel_consumed_since_restart", "value": 0.103335}
{"timestamp": 1504199167.371, "name": "headlamp_status", "value": false}
{"timestamp": 1504199167.372, "name": "high_beam_status", "value": false}
{"timestamp": 1504199167.373, "name": "windshield_wiper_status", "value": false}
{"timestamp": 1504199167.374, "name": "door_status", "value": "passenger", "event": false}
{"timestamp": 1504199167.375, "name": "door_status", "value": "driver", "event": false}
{"timestamp": 1504199167.376, "name": "door_status", "value": "right_rear", "event": false}
{"timestamp": 1504199167.377, "name": "door_status", "value": "left_rear", "event": false}
{"timestamp": 1504199167.378, "name": "steering_wheel_angle", "value": 0.0}
{"timestamp": 1504199167.378, "name": "torque_at_transmission", "value": 0.0}
{"timestamp": 1504199167.378, "name": "engine_speed", "value": 0.0}
{"timestamp": 1504199167.378, "name": "vehicle_speed", "value": 0.0}
{"timestamp": 1504199167.378, "name": "accelerator_pedal_position", "value": 0.0}
{"timestamp": 1504199167.379, "name": "odometer", "value": 0.0}
{"timestamp": 1504199167.38, "name": "fuel_consumed_since_restart", "value": 0.1035}
{"timestamp": 1504199167.487, "name": "steering_wheel_angle", "value": 0.0}
{"timestamp": 1504199167.488, "name": "torque_at_transmission", "value": 0.0}
{"timestamp": 1504199167.489, "name": "engine_speed", "value": 0.0}
{"timestamp": 1504199167.49, "name": "vehicle_speed", "value": 0.0}
{"timestamp": 1504199167.491, "name": "accelerator_pedal_position", "value": 0.0}
{"timestamp": 1504199167.492, "name": "odometer", "value": 0.0}
{"timestamp": 1504199167.493, "name": "fuel_consumed_since_restart", "value": 0.103665}
{"timestamp": 1504199167.577, "name": "fuel_level", "value": 99.0}
{"timestamp": 1504199167.597, "name": "steering_wheel_angle", "value": 0.0}
{"timestamp": 1504199167.598, "name": "torque_at_transmission", "value": 0.0}
{"timestamp": 1504199167.599, "name": "engine_speed", "value": 0.0}
{"timestamp": 1504199167.6, "name": "vehicle_speed", "value": 0.0}
{"timestamp": 1504199167.601, "name": "accelerator_pedal_position", "value": 0.0}
{"timestamp": 1504199167.602, "name": "odometer", "value": 0.0}
{"timestamp": 1504199167.603, "name": "fuel_consumed_since_restart", "value": 0.10383}
{"timestamp": 1504199167.707, "name": "steering_wheel_angle", "value": 0.0}
{"timestamp": 1504199167.708, "name": "torque_at_transmission", "value": 0.0}
{"timestamp": 1504199167.709, "name": "engine_speed", "value": 0.0}
{"timestamp": 1504199167.71, "name": "vehicle_speed", "value": 0.0}
{"timestamp": 1504199167.711, "name": "accelerator_pedal_position", "value": 0.0}
{"timestamp": 1504199167.712, "name": "odometer", "value": 0.0}
{"timestamp": 1504199167.713, "name": "fuel_consumed_since_restart", "value": 0.103995}
{"timestamp": 1504199167.808, "name": "steering_wheel_angle", "value": 0.0}
{"timestamp": 1504199167.809, "name": "torque_at_transmission", "value": 0.0}
{"timestamp": 1504199167.81, "name": "engine_speed", "value": 0.0}
{"timestamp": 1504199167.811, "name": "vehicle_speed", "value": 0.0}
{"timestamp": 1504199167.812, "name": "accelerator_pedal_position", "value": 0.0}
{"timestamp": 1504199167.813, "name": "odometer", "value": 0.0}
{"timestamp": 1504199167.814, "name": "fuel_consumed_since_restart", "value": 0.104145}
{"timestamp": 1504199167.918, "name": "steering_wheel_angle", "value": 0.0}
{"timestamp": 1504199167.919, "name": "torque_at_transmission", "value": 0.0}

**Closed by emarsman** 2017-08-31 17:12 UTC
